name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 'lts/*'
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Run linter
      run: npm run lint
      
    - name: Build project
      run: npm run build
